version: '3.9'

services:
  db:
    image: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: zlagoda
    volumes:
      - zlagoda_data:/var/utils/postgresql/data
    ports:
      - "3211:5432"
volumes:
  zlagoda_data:
